export const response = {
  success: true,
  data: [
    { equipo: "Arsenal", GF: 58, GC: 25, puntos: 60 },
    { equipo: "Manchester City", GF: 65, GC: 22, puntos: 63 },
    { equipo: "Liverpool", GF: 55, GC: 30, puntos: 78 },
    { equipo: "Chelsea", GF: 50, GC: 35, puntos: 52 },
    { equipo: "Tottenham Hotspur", GF: 48, GC: 37, puntos: 49 },
    { equipo: "Manchester United", GF: 47, GC: 38, puntos: 45 },
    { equipo: "Newcastle United", GF: 44, GC: 36, puntos: 43 },
    { equipo: "Brighton & Hove Albion", GF: 42, GC: 39, puntos: 40 },
    { equipo: "Aston Villa", GF: 40, GC: 41, puntos: 38 },
    { equipo: "West Ham United", GF: 39, GC: 43, puntos: 35 },
    { equipo: "Leicester City", GF: 37, GC: 44, puntos: 33 },
    { equipo: "Wolverhampton Wanderers", GF: 35, GC: 45, puntos: 32 },
    { equipo: "Crystal Palace", GF: 34, GC: 46, puntos: 30 },
    { equipo: "Everton", GF: 33, GC: 47, puntos: 28 },
    { equipo: "Fulham", GF: 31, GC: 49, puntos: 27 },
    { equipo: "Brentford", GF: 30, GC: 50, puntos: 25 },
    { equipo: "Bournemouth", GF: 29, GC: 52, puntos: 23 },
    { equipo: "Nottingham Forest", GF: 28, GC: 54, puntos: 21 },
    { equipo: "Sheffield United", GF: 25, GC: 57, puntos: 18 },
  ],
};
